library(dplyr)

# Set wd to project folder destination
setwd("C:/Users/alec.blase/OneDrive - HHS Office of the Secretary/Desktop/hospital-index-app")

load("data/index_items_df.RData") # Generated by "Interop Item Level App Data Import"


### This crosswalk is designed to clarify labels for figures.
Index<-c("Core","Core", "Core", "Core","Pathfinder", "Pathfinder", "Pathfinder", "Pathfinder", "Pathfinder","Friction", "Friction","Friction","Friction")
Label<-c("Composite","Clinical Interoperability", "Data Availability & Use", "Breadth", "Composite","Clinician/Health System API", "Patient Engagement", "Social Determinants of Health", "Public Health", "Composite","Barriers to Exchange", "Multiple Methods to Exchange", "Information Blocking")
Component<-c("Composite","ClinInteropFx", "DataUse", "breadth_of_exchange", "Composite","API", "PatientEngagement", "SDOH", "PublicHealth", "Composite","Barriers", "Methods", "InfoBlocking")
IndexComponent<-data.frame(Index,Component, Label)

##Rename items
'''
dfItem <- dfItem %>%
  rename("Year" = Year,
         "Find Data Electronically" = Find,
         "Send Data Electronically" = Send,
         "Receive Data Electronically" = Receive,
         "Integrate Data without Manual Effort" = Integrate,
         "Information Available to Clinicians" = Available,
         "Information Used by Clinicians" = Used,
         "Syndromic Surveillance Reporting by EHR / HIE" = PH_SS,
         "Immunization Data Reporting by EHR / HIE" = PH_IRR,
         "Electronic Case Reporting by EHR / HIE" = PH_ECR,
         "Public Health Registry Reporting by EHR / HIE" = PH_PHR,
         "Clinical Registry Reporting by EHR / HIE" = PH_CDR,
         "Electronic Lab Result Reporting by EHR / HIE" = PH_ERL,
         "Hospital Capacity Reporting by EHR / HIE" = PH_HCR,
         "Enable Patient Information Downloading" = PE_Download,
         "Enable Patient Information Importing" = PE_Import,
         "Enable Sending Patient Information" = PE_Send,
         "Enable Patient Access to Apps via APIs" = PE_API,
         "Enable Patient Access to Apps via FHIR" = PE_FHIR,
         "Enable Submission of Patient Generated Data via FHIR" = PE_PGHDFHIR,
         "Send Hospitals Information" = HospitalSend,
         "Receive Information from Hospitals" = HospitalReceive,
         "Send Ambulatory Providers Information" = AmbSend,
         "Receive Information from Ambulatory Providers" = AmbReceive,
         "Send Long-term Care Patient Information" = LTPACSend,
         "Receive Information from Long-term Care" = LTPACReceive,
         "Send Behavioral Health Patient Information" = BHSend,
         "Receive Information from Behavioral Health" = BHReceive,
         "Barriers to Receiving Information" = Barrier_Receive,
         "Barriers to Sending Information" = Barrier_Send,
         "Other Barriers to Exchange" = Barrier_Other,
         "Numerous Methods to Find Information" = MFind,
         "Numerous Methods to Send Information" = MSend,
         "Numerours Methods to Receive Information" = MReceive,
         "Receive SDoH Information from Other Organizations" = SDOH_Received,
         "Use SDoH Information from Other Organizations for Individual Care"=SDOH_Used_Ind,
         "Use SDoH Information from Other Organizations for Population Health"=SDOH_Used_Pop,
         "Provide EHR Data to Third-Party Apps - Clinical" = API_SendEHR_clin,
         "Integrate Third-Party Data into EHR - Clinical" = API_Integrate_clin,
         "Provide EHR Data to Third-Party Apps - Administrative" = API_SendEHR_admin,
         "Integrate Third-Party Data into EHR - Administrative" = API_Integrate_admin,
         "Experience Information Blocking by EHR Developers"=IB_Extant_EHR,
         "Experience Information Blocking by Healthcare Providers"=IB_Extant_Prov,
         "Experience Information Blocking by Health Information Networks"=IB_Extant_HIE)
'''

### This crosswalk creates groups of items for the item table figure.
itemComponentCrossWalk <- data.frame(item = colnames(dfItem), stringsAsFactors = FALSE)
itemComponentCrossWalk$component<-c(
  "Clinical Interoperability","Clinical Interoperability","Clinical Interoperability","Clinical Interoperability",
  "Data Availability & Use","Data Availability & Use",
  "Patient Engagement","Patient Engagement","Patient Engagement","Patient Engagement","Patient Engagement",
  "Public Health","Public Health","Public Health","Public Health","Public Health","Public Health","Public Health",
  "Barriers to Exchange","Barriers to Exchange","Barriers to Exchange",
  "Multiple Methods to Exchange","Multiple Methods to Exchange","Multiple Methods to Exchange",
  "Information Blocking","Information Blocking","Information Blocking",
  "None","None","None",
  "Breadth", "Breadth", "Breadth", "Breadth", "Breadth", "Breadth", "Breadth", "Breadth",
  "Patient Engagement",
  "Social Determinants of Health", "Social Determinants of Health", "Social Determinants of Health", 
  "Clinician/Health System API","Clinician/Health System API","Clinician/Health System API","Clinician/Health System API"
)


itemComponentCrossWalk$index<-c(
  "Core","Core","Core","Core",
  "Core","Core",
  "Pathfinder","Pathfinder","Pathfinder","Pathfinder","Pathfinder",
  "Pathfinder","Pathfinder","Pathfinder","Pathfinder","Pathfinder","Pathfinder","Pathfinder",
  "Friction","Friction","Friction",
  "Friction","Friction","Friction",
  "Friction","Friction","Friction",
  "None","None","None",
  "Core", "Core", "Core", "Core", "Core", "Core", "Core", "Core",
  "Pathfinder",
  "Pathfinder", "Pathfinder", "Pathfinder", 
  "Pathfinder","Pathfinder","Pathfinder","Pathfinder"
)

save(IndexComponent, file="C:/Users/alec.blase/OneDrive - HHS Office of the Secretary/Desktop/hospital-index-app/data/IndexComponentCrosswalk.RData")
save(itemComponentCrossWalk, file="C:/Users/alec.blase/OneDrive - HHS Office of the Secretary/Desktop/hospital-index-app/data/ItemComponentCrosswalk.RData")
